env:
    browser: true
    commonjs: true
    es6: true
extends:
    - "eslint:recommended"
    - "plugin:cypress/recommended"
    
parserOptions:
    ecmaVersion: 2018
    sourceType: module

plugins:
    - "cypress"

rules:
    indent:
        - error
        - 4
    linebreak-style:
        - error
        - unix
    quotes:
        - error
        - double
    semi:
        - error
        - always
