describe('Verify available options in Advanced Search', function() {
	let fixtures = {}
	before(() => {
		Cypress.Promise.all([
			cy.fixture(Cypress.env("ORG") + "/UNSWLibCol").then(fx => (fixtures["UNSWLibCol"] = fx))
		])
	})
	beforeEach(function(){
		cy.visit(fixtures["UNSWLibCol"].primoUATUrl)
	
	})
	context('All the expected options for Advanced Search will display', function () {
		it('Checking the "Title" section', function () {
			cy.get('span[translate="label.advanced_search"]')
			  .click()
			cy.get('span[translate="search-advanced.scope.option.nui.advanced.index.title"]')
			  .should('have.text','TitleTitleTitleTitle')
			cy.get('md-select[aria-label="Select Search Field for complex line number 1: Title"]')
			  .get('span[class="_md-select-icon"]')
			  .click({ multiple: true ,force: true})
			cy.get('span[translate="search-advanced.scope.option.nui.advanced.index.any"]')
			  .should('have.text','Any fieldAny field')
			cy.get('span[translate="search-advanced.scope.option.nui.advanced.index.title"]')
			  .should('have.text','TitleTitleTitleTitle')
			cy.get('span[translate="search-advanced.scope.option.nui.advanced.index.creator"]')
			  .should('have.text','Author/creatorAuthor/creator')
			cy.get('span[translate="search-advanced.scope.option.nui.advanced.index.sub"]')
			  .should('have.text','SubjectSubject')
			cy.get('span[translate="search-advanced.scope.option.nui.advanced.index.isbn"]')
			  .should('have.text','ISBNISBN')
			cy.get('span[translate="search-advanced.scope.option.nui.advanced.index.issn"]')
			  .should('have.text','ISSNISSN')
			cy.get('span[translate="search-advanced.scope.option.nui.advanced.index.lsr30"]')
			  .should('have.text','Database CategoriesDatabase Categories')
		})  
		it('Checking the "contains" section', function () {
			cy.get('span[translate="label.advanced_search"]')
			  .click()
			cy.get('span[translate="search-advanced.precisionOperator.option.contains"]')
			  .should('have.text','containscontainscontainscontains')
			cy.get('md-select[aria-label="Select Precision Operation for complex line number 1: contains"]')
			  .get('span[class="_md-select-icon"]')
			  .click({ multiple: true ,force: true})
			cy.get('span[translate="search-advanced.precisionOperator.option.contains"]')
			  .should('have.text','containscontainscontainscontains')
			cy.get('span[translate="search-advanced.precisionOperator.option.exact"]')
			  .should('have.text','is (exact)is (exact)')
			cy.get('span[translate="search-advanced.precisionOperator.option.startswith"]')
			  .should('have.text','starts withstarts with')
		})  
		it('Checking the "AND" section', function () {
			cy.get('span[translate="label.advanced_search"]')
			  .click()
			cy.get('span[translate="search-advanced.boolOperator.option.AND"]')
			  .should('have.text','ANDAND')
			cy.get('md-select[aria-label="Select Boolean Operator for complex line number 1: AND"]')
			  .get('span[class="_md-select-icon"]')
			  .click({ multiple: true ,force: true})
			cy.get('span[translate="search-advanced.boolOperator.option.AND"]')
			  .should('have.text','ANDAND')
			cy.get('span[translate="search-advanced.boolOperator.option.OR"]')
			  .should('have.text','OR')
			cy.get('span[translate="search-advanced.boolOperator.option.NOT"]')
			  .should('have.text','NOT')
		})	  
		it('Checking the "Recourse Type" section', function () {
			cy.get('span[translate="label.advanced_search"]')
			  .click()
			cy.get('span[translate="search-advanced.mediaType.option.all_items"]')
			  .should('have.text','All typesAll types')
			cy.get('md-select[aria-label="Resource Type: All types"]')
			  .get('span[class="_md-select-icon"]')
			  .click({ multiple: true ,force: true})
			cy.get('span[translate="search-advanced.mediaType.option.all_items"]')
			  .should('have.text','All typesAll types')
			cy.get('span[translate="search-advanced.mediaType.option.articles"]')
			  .should('have.text','Articles')
			cy.get('span[translate="search-advanced.mediaType.option.audio_video"]')
			  .should('have.text','Audio Visual')
			cy.get('span[translate="search-advanced.mediaType.option.books"]')
			  .should('have.text','Books')
			cy.get('span[translate="search-advanced.mediaType.option.databases"]')
			  .should('have.text','Databases')
			cy.get('span[translate="search-advanced.mediaType.option.Dissertations"]')
			  .should('have.text','Dissertations')
			cy.get('span[translate="search-advanced.mediaType.option.journals"]')
			  .should('have.text','Journals')
		})
		it('Checking the "Publication Date" section', function () {
			cy.get('span[translate="label.advanced_search"]')
			  .click()
			cy.get('span[translate="search-advanced.publicationDate.option.all_items"]')
			  .should('have.text','Any yearAny year')
			cy.get('md-select[aria-label="Publication Date: Any year"]')
			  .get('span[class="_md-select-icon"]')
			  .click({ multiple: true ,force: true})
			cy.get('span[translate="search-advanced.publicationDate.option.y1"]')
			  .should('have.text','Last year')
			cy.get('span[translate="search-advanced.publicationDate.option.y2"]')
			  .should('have.text','Last 2 years')
			cy.get('span[translate="search-advanced.publicationDate.option.y5"]')
			  .should('have.text','Last 5 years')
			cy.get('span[translate="search-advanced.publicationDate.option.y10"]')
			  .should('have.text','Last 10 years')
			cy.get('span[translate="nui.search-advanced.publicationDate.option.specificDate"]')
			  .should('have.text','Specific date')
			cy.get('span[translate="search-advanced.publicationDate.option.all_items"]')
			  .should('have.text','Any yearAny year')
			cy.get('span[translate="search-advanced.publicationDate.option.y20"]')
			  .should('have.text','Last 20 years') 
		})
			
			
			
	
		
		
	})
})
